language: objective-c
osx_image: xcode8
script:
- bin/xctester tests/*.swift >$TMPDIR/output.txt 2>/dev/null || true
- sed -i '' 's/0\.[0-9]* /0 /' $TMPDIR/output.txt
- diff tests/expected-output.txt $TMPDIR/output.txt
